# Generated by Django 6.0 on 2026-09-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbnails', '0002_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot', models.CharField(help_text='e.g., 09:00 AM - 10:00 AM', max_length=50)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='time_slot',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
