# Generated by Django 6.0 on 2026-09-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbnails', '0004_service_rename_uploaded_at_galleryimage_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='inspiration_image',
            field=models.ImageField(blank=True, null=True, upload_to='inspiration_images/'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time_slot',
            field=models.CharField(default='09:00 AM', max_length=50),
            preserve_default=False,
        ),
    ]
